CREATE TABLE IF NOT EXISTS roles (
     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
     name VARCHAR(50)                                        NOT NULL
    );

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    username VARCHAR(30) UNIQUE                            NOT NULL,
    password VARCHAR(80)                                   NOT NULL,
    email VARCHAR(30) UNIQUE                               NOT NULL
    );

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(50) UNIQUE                                NOT NULL
    );

CREATE TABLE IF NOT EXISTS cities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(50) UNIQUE                                NOT NULL
    );

CREATE TABLE IF NOT EXISTS users_roles (
    user_id               bigint not null,
    role_id               int not null,
    primary key (user_id, role_id),
    foreign key (user_id) references users (id),
    foreign key (role_id) references roles (id)
    );

CREATE TABLE IF NOT EXISTS locations (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(50)                                        NOT NULL,
    latitude FLOAT                                          NOT NULL,
    longitude FLOAT                                         NOT NULL,
    radius BIGINT                                           NOT NULL
    );

CREATE TABLE IF NOT EXISTS places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    title VARCHAR(30) UNIQUE                               NOT NULL,
    description VARCHAR(300)                               NOT NULL,
    filename VARCHAR(300),
    latitude FLOAT                                          NOT NULL,
    longitude FLOAT                                         NOT NULL,
    creator_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    category_id BIGINT REFERENCES categories (id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS comments (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    text  VARCHAR(1000)                                      NOT NULL,
    author_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    place_id BIGINT REFERENCES places (id) ON DELETE CASCADE,
    created TIMESTAMP WITHOUT TIME ZONE                      NOT NULL
    );

CREATE TABLE IF NOT EXISTS places_comments (
    place_id               BIGINT NOT NULL,
    comment_id             BIGINT NOT NULL,
    PRIMARY KEY (place_id, comment_id),
    FOREIGN KEY (place_id) REFERENCES places (id),
    FOREIGN KEY (comment_id) REFERENCES comments (id)
    );

CREATE TABLE IF NOT EXISTS ways (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    title VARCHAR(30) UNIQUE                                 NOT NULL,
    description VARCHAR(300)                                 NOT NULL,
    creator_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    location_id BIGINT REFERENCES places (id) ON DELETE CASCADE,
    created_on TIMESTAMP WITHOUT TIME ZONE                   NOT NULL
    );

CREATE TABLE IF NOT EXISTS ways_places (
    way_id                 BIGINT NOT NULL,
    place_id               BIGINT NOT NULL,
    PRIMARY KEY (way_id, place_id),
    FOREIGN KEY (way_id) REFERENCES ways (id),
    FOREIGN KEY (place_id) REFERENCES places (id)
    );





